---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/25 0025 上午 11:45
---

-----------------for 循环
for i = 1, 3 do
    io.write(i);

end
-----------------for 循环每次变量更改的大小
for a = 1, 10, 2 do
    print(a)
end

-----------------函数
function myFunc1()
    print("hello function")
end

myFunc1();
-----------------带参数函数
a = 1
b = 2
function myFunc2(par1, par2)
    return par1 + par2
end
c = myFunc2(a, b)
print(c)

-----------------带参数函数 返回多个变量

a = 1
b = 2
function myFunc3(A, B)
    return A, B
end
c, d = myFunc3(a, b) --c会等于返回的第一个，在此倒转过来即为2
print(c, d)


-----------------逻辑控制语句

a = 10

if a == 10 then

    print("我是10")

elseif a == 11 then

    print("我是11")

else

    print("Else")

end

-----------------引用类型

linbc = {}
linbc.sex = "男";
linbc.age = 27;
print(linbc, linbc.sex, linbc["age"])
A = linbc
print(A["sex"])

for i, v in pairs(linbc) do
    print(i, v)
end
-----------------数组 下标1开始
arr = { 1, 2, 3, "a", 'b', linbc }

for i, v in pairs(arr) do

    print(i, v)

end


 table.insert(arr,88)

 table.foreach(arr,function(i,v) print(i,v) end)

 print(arr[6])

 table.foreach(arr,function(i,v) print(i,v) end)




