---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/24 0024 下午 5:25
---
-- Redis 设置值脚本       eval "return redis.call('SET',KEYS[1],ARGV[1])" 1 www 200
---Redis 获取值脚本       eval "return redis.call('get','www')" 0


local keys = redis.call('keys', ARGV[1])
for i = 1, #keys, 5000 do
    redis.call('del', unpack(keys, i, math.min(i + 4999, #keys)))
end
return #keys " 0 PAIR_KLINE_VOLUMN:*